name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25b
        local-cache: true
    
    - uses: lukka/get-cmake@latest  
      with:
        useLocalCache: true
        useCloudCache: false
        cmakeVersion: 3.16.3
    
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew app:assembleDebug
